// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMacOSSecurityStatus():Promise<Record<string, any>>;

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function EncodeIndexedPNG(arg1:string,arg2:number,arg3:number):Promise<string>;

export function IsDir(arg1:string):Promise<boolean>;

export function ListImages(arg1:string):Promise<Array<string>>;

export function OpenImageDialog():Promise<Array<string>>;

export function OpenMacOSSecuritySettings():Promise<void>;

export function PushPendingPaths(arg1:Array<string>):Promise<void>;

export function ReadImage(arg1:string):Promise<string>;

export function ReadThumbnail(arg1:string,arg2:number):Promise<string>;

export function SaveImage(arg1:string,arg2:string):Promise<void>;

export function SaveImageDialog(arg1:string,arg2:string):Promise<string>;

export function TakePendingOpenPaths():Promise<Array<string>>;
