// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMacOSSecurityStatus() {
  return window['go']['backend']['App']['CheckMacOSSecurityStatus']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['backend']['App']['CopyImageToClipboard'](arg1);
}

export function EncodeIndexedPNG(arg1, arg2, arg3) {
  return window['go']['backend']['App']['EncodeIndexedPNG'](arg1, arg2, arg3);
}

export function IsDir(arg1) {
  return window['go']['backend']['App']['IsDir'](arg1);
}

export function ListImages(arg1) {
  return window['go']['backend']['App']['ListImages'](arg1);
}

export function OpenImageDialog() {
  return window['go']['backend']['App']['OpenImageDialog']();
}

export function OpenMacOSSecuritySettings() {
  return window['go']['backend']['App']['OpenMacOSSecuritySettings']();
}

export function PushPendingPaths(arg1) {
  return window['go']['backend']['App']['PushPendingPaths'](arg1);
}

export function ReadImage(arg1) {
  return window['go']['backend']['App']['ReadImage'](arg1);
}

export function ReadThumbnail(arg1, arg2) {
  return window['go']['backend']['App']['ReadThumbnail'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['backend']['App']['SaveImage'](arg1, arg2);
}

export function SaveImageDialog(arg1, arg2) {
  return window['go']['backend']['App']['SaveImageDialog'](arg1, arg2);
}

export function TakePendingOpenPaths() {
  return window['go']['backend']['App']['TakePendingOpenPaths']();
}
