// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePreviews(arg1) {
  return window['go']['backend']['App']['GeneratePreviews'](arg1);
}

export function GetDefaultOutputDirectory() {
  return window['go']['backend']['App']['GetDefaultOutputDirectory']();
}

export function InspectImages(arg1) {
  return window['go']['backend']['App']['InspectImages'](arg1);
}

export function ProcessImage(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ProcessImage'](arg1, arg2, arg3);
}

export function ProcessImages(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ProcessImages'](arg1, arg2, arg3);
}

export function SelectImageFiles() {
  return window['go']['backend']['App']['SelectImageFiles']();
}

export function SelectImageFolder() {
  return window['go']['backend']['App']['SelectImageFolder']();
}

export function SelectOutputDirectory() {
  return window['go']['backend']['App']['SelectOutputDirectory']();
}

export function TriggerGC() {
  return window['go']['backend']['App']['TriggerGC']();
}
