// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GeneratePreviews(arg1:Array<string>):Promise<void>;

export function GetDefaultOutputDirectory():Promise<string>;

export function InspectImages(arg1:Array<string>):Promise<Array<backend.ImageFileInfo>>;

export function ProcessImage(arg1:string,arg2:backend.ProcessingOptions,arg3:string):Promise<backend.ProcessResult>;

export function ProcessImages(arg1:Array<string>,arg2:backend.ProcessingOptions,arg3:string):Promise<backend.BatchProcessResult>;

export function SelectImageFiles():Promise<Array<string>>;

export function SelectImageFolder():Promise<Array<string>>;

export function SelectOutputDirectory():Promise<string>;

export function TriggerGC():Promise<void>;
