// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOpenedFile() {
  return window['go']['main']['App']['GetOpenedFile']();
}

export function GetVideoDuration(arg1) {
  return window['go']['main']['App']['GetVideoDuration'](arg1);
}

export function OpenVideoFile() {
  return window['go']['main']['App']['OpenVideoFile']();
}

export function SetOpenedFile(arg1) {
  return window['go']['main']['App']['SetOpenedFile'](arg1);
}
