// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVideoDuration(arg1:string):Promise<number>;

export function OpenVideoFile():Promise<string>;
