// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOpenedFile():Promise<string>;

export function GetVideoDuration(arg1:string):Promise<number>;

export function OpenVideoFile():Promise<string>;

export function SetOpenedFile(arg1:string):Promise<void>;
